# Generated by Django 5.0 on 2026-03-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('IMPORTACION', 'Importación masiva Excel'), ('CREAR_GRUPO', 'Crear grupo'), ('EDITAR_GRUPO', 'Editar grupo'), ('CREAR_DIVISION', 'Crear división'), ('EDITAR_DIVISION', 'Editar división'), ('CREAR_PROGRAMA', 'Crear programa'), ('EDITAR_PROGRAMA', 'Editar programa'), ('EDITAR_PERIODO', 'Editar periodo'), ('CREAR_USUARIO', 'Crear usuario'), ('EDITAR_USUARIO', 'Editar usuario'), ('ACTIVAR_USUARIO', 'Activar usuario'), ('DESACTIVAR_USUARIO', 'Desactivar usuario'), ('ASIGNAR_TUTOR', 'Asignar tutor a grupo')], max_length=30),
        ),
    ]
